name: auto commit and push

on:
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: modify files
        run: echo "Update on $(date)" >> update.log

      - name: commit changes
        run: |
          git config --global user.email "maxshen1212@gmail.com"
          git config --global user.name "Chih-Han Shen"
          git add .
          git commit -m "Automated commit on $(date)"

      - name: push code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
      - name: use action to auto commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated commit on $(date)"
          branch: main
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com