name: node test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Set up Node.js
    #     uses: actions/setup-node@v6
    #     with:
    #       node-version: 20
    #   - run: npm install
    #   - run: npm test
