name: compress-and-upload

on:
  push:
    branches:
      - main
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: compress file
        run: |
          mkdir compressed
          tar -czf compressed/files.tar.gz .
      - name: upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: compressed-files
          path: compressed/files.tar.gz
